### ISSUE TITLE
error

### ISSUE THREAD

**Issue by darkside69696** [Not-Cyrus/GoGuardian#7] opened 2021-02-28 15:23 UTC
How can I fix this?
![cxzcz](https://user-images.githubusercontent.com/79799411/109423824-40ff2e80-79e1-11eb-97da-6fe58295f3dd.PNG)

**Comment by darkside69696** [comment] 2021-02-28 16:32
![cxzczx](https://user-images.githubusercontent.com/79799411/109425912-f2ef2880-79ea-11eb-8d10-3356c89e1582.PNG)

**Comment by lxi1400** [comment] 2021-02-28 18:06
the issue is legit right in ur face

**Comment by darkside69696** [comment] 2021-02-28 18:09
=[[

**Comment by Not-Cyrus** [comment] 2021-02-28 18:13
delete the discordgo version from your gopath (I'm currently on phone or I would write how) so just use Google for that if you don't know how (default path is your user directory\go)

then run this V

go get github.com/bwmarrin/discordgo@v0.22.0

**Comment by darkside69696** [comment] 2021-02-28 18:27
![xzczx](https://user-images.githubusercontent.com/79799411/109429234-f68aab80-79fa-11eb-82a2-4666defff649.PNG)
![zxczxcz](https://user-images.githubusercontent.com/79799411/109429243-fa1e3280-79fa-11eb-803f-52565f5207cf.PNG)

**Comment by Not-Cyrus** [comment] 2021-02-28 18:38
Did you forget to run this command?
```YAML
db.whitelist.insertOne({useless: "github.com/Not-Cyrus"})
```

**Comment by darkside69696** [comment] 2021-02-28 18:57
![sdada](https://user-images.githubusercontent.com/79799411/109429979-20de6800-79ff-11eb-86f9-31cced5c7974.PNG)
hmm I got this message

**Comment by Not-Cyrus** [comment] 2021-02-28 19:19
now you can run the bot again and it should work

**Comment by darkside69696** [comment] 2021-02-28 19:42
ok, ty, can I host it on repl.it?

**Comment by Not-Cyrus** [comment] 2021-02-28 20:04
I've never tried before, so you might but I would never recommend hosting on repl.it (coming from someone making a repl.it scraper right now lol)

**Comment by darkside69696** [comment] 2021-02-28 20:13
hmm, do you know a good vps ?

**Comment by Not-Cyrus** [comment] 2021-02-28 21:07
Digital Ocean is a decent one, but you'll have to do research on your own to see what fits your needs (I personally just self host)

**Comment by lxi1400** [comment] 2021-02-28 21:26
kys

**Comment by kaihgg** [comment] 2021-03-01 02:00
same

**Comment by Not-Cyrus** [comment] 2021-03-01 19:49
closed as it's been almost 24 hours, issue seems fixed.

**Closed by Not-Cyrus** 2021-03-01 19:49 UTC

**Comment by unrapeable** [comment] 2021-03-04 14:58
@darkside69696 how were u even able to run it on repl
